apiVersion: v1
kind: Service
metadata:
  name: todoservice
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31111
    protocol : TCP
  selector:
    app: todo
